[project]
name = "telegram-media"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "aiogram==3.25.0",
    "aiohttp==3.13.3",
    "aiosqlite==0.22.1",
    "openai==2.20.0",
    "pydantic-settings>=2.9",
]
